-- populate table
INSERT INTO EMPLOYEES (FIRSTNAME, LASTNAME, ROLE, DEPARTMENT, SALARY) VALUES ('Daniel', 'Wind', 'Software Architect', 'Engineering', 100000);
INSERT INTO EMPLOYEES (FIRSTNAME, LASTNAME, ROLE, DEPARTMENT, SALARY) VALUES ('Maurice', 'Moss', 'IT Guy', 'Engineering', 90000);
INSERT INTO EMPLOYEES (FIRSTNAME, LASTNAME, ROLE, DEPARTMENT, SALARY) VALUES ('Roy', 'Trenneman', 'IT Guy', 'Engineering', 90000);
INSERT INTO EMPLOYEES (FIRSTNAME, LASTNAME, ROLE, DEPARTMENT, SALARY) VALUES ('Jen','Barber','Manager','Human Resources',80000);
INSERT INTO EMPLOYEES (FIRSTNAME, LASTNAME, ROLE, DEPARTMENT, SALARY) VALUES ('Jason','Jones','Representative','Customer Service',70000);
INSERT INTO EMPLOYEES (FIRSTNAME, LASTNAME, ROLE, DEPARTMENT, SALARY) VALUES ('Carrie','Bradshaw','Representative','Customer Service',70000);
INSERT INTO EMPLOYEES (FIRSTNAME, LASTNAME, ROLE, DEPARTMENT, SALARY) VALUES ('Samantha','Cole','Representative','Customer Service',70000);
INSERT INTO EMPLOYEES (FIRSTNAME, LASTNAME, ROLE, DEPARTMENT, SALARY) VALUES ('John','Smith','Engineer','Engineering',75000);
INSERT INTO EMPLOYEES (FIRSTNAME, LASTNAME, ROLE, DEPARTMENT, SALARY) VALUES ('Hannah','Barbera','Representative','Customer Service',70000);
INSERT INTO EMPLOYEES (FIRSTNAME, LASTNAME, ROLE, DEPARTMENT, SALARY) VALUES ('Rick','Moranis','Maanger','Customer Service',80000);
INSERT INTO EMPLOYEES (FIRSTNAME, LASTNAME, ROLE, DEPARTMENT, SALARY) VALUES ('James','Gosling','Developer','Engineering',90000);
INSERT INTO EMPLOYEES (FIRSTNAME, LASTNAME, ROLE, DEPARTMENT, SALARY) VALUES ('Phillip','Banks','Guard','Security',60000);
INSERT INTO EMPLOYEES (FIRSTNAME, LASTNAME, ROLE, DEPARTMENT, SALARY) VALUES ('Fred','Flintstone','Representative','Customer Service',70000);
INSERT INTO EMPLOYEES (FIRSTNAME, LASTNAME, ROLE, DEPARTMENT, SALARY) VALUES ('Franz','List','Guard','Security',50000);
INSERT INTO EMPLOYEES (FIRSTNAME, LASTNAME, ROLE, DEPARTMENT, SALARY) VALUES ('Barney','Gomez','Representative JR','Customer Service',50000);

