-- populate database
INSERT INTO MOVIES (TITLE, PUBLISHER, RELEASE_DATE) VALUES ('Cast Away','20th Century Fox','2000-12-07');
INSERT INTO MOVIES (TITLE, PUBLISHER, RELEASE_DATE) VALUES ('Shrek the Third','Paramount Pictures','2007-05-18');
INSERT INTO MOVIES (TITLE, PUBLISHER, RELEASE_DATE) VALUES ('Puss In Boots','Paramount Pictures','2011-10-28');
INSERT INTO MOVIES (TITLE, PUBLISHER, RELEASE_DATE) VALUES ('Mission Impossible Ghost Protocol','Paramount Pictures','2011-12-16');
INSERT INTO MOVIES (TITLE, PUBLISHER, RELEASE_DATE) VALUES ('Pirates of the Caribbean: The Curse of the Black Pearl','Walt Disney Pictures','2003-07-09');
INSERT INTO MOVIES (TITLE, PUBLISHER, RELEASE_DATE) VALUES ('Mickey Blue Eyes','Castle Rock Entertainment','1999-08-17');
INSERT INTO MOVIES (TITLE, PUBLISHER, RELEASE_DATE) VALUES ('Oceans Twelve','Warner Bros. Pictures','2004-12-10');
INSERT INTO MOVIES (TITLE, PUBLISHER, RELEASE_DATE) VALUES ('Fight Club','20th Century Fox','1999-10-15');
INSERT INTO MOVIES (TITLE, PUBLISHER, RELEASE_DATE) VALUES ('Rush Hour','New Line Cinema','1998-07-18');
INSERT INTO MOVIES (TITLE, PUBLISHER, RELEASE_DATE) VALUES ('Demolition Man','Warner Bros. Pictures','1993-10-08');